**IMPORT THE MODULE**

In [1]:
import psycopg2

**CONNECT TO THE POSTGRES DATABASE**
- Use the connect() method with the required arguments to connect to an existing Postgres server

In [2]:
try: 
    conn = psycopg2.connect(host = 'localhost',
                            port = '5432',
                            user = 'postgres',
                            password = 'password')
except Exeception as error:
    print(error)

**SET autocommit to true**
- This means that after each call, commit that one action and do not open the transaction for any other action.

In [3]:
conn.set_session(autocommit = True)

**Use the cursor() method**
- Create a cursor object using the connection object returned by the connect method to execute PostgreSQL queries from Python.

In [4]:
try:
    cur = conn.cursor()
except Exception as error:
    print(error)

**Use the execute() method**
- The execute() methods run the SQL query and return the result.

I created a table named naija_top5, It includes the id, name, release date, artist name and list of songs in the my top 5 Nigerian albums of 2021. 

- **TABLE NAME** : naija_top5
- **column 0**   : album_id
- **column 1**   : album_name
- **column 2**   : release_date
- **column 3**   : artist_name
- **column 4**   : song_name

In [5]:
try:
    cur.execute('CREATE TABLE IF NOT EXISTS naija_top5 (album_id int, \
                                                          album_name varchar(200), \
                                                          release_date date, \
                                                          artist_name varchar(200), \
                                                          song_name text[])')
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', \
                ['Reckless', 'Ginger', 'Longtime', 'Mighty Wine', 'Blessed', 'Smile', 'Piece of Me', 'No Stress', \
                 'True Love', 'Sweet One', 'Essence', 'Roma', 'Gyrate', 'Grace']))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES(%s, %s, %s, %s, %s)', \
                (2, 'A Better Time', '2020-11-12', 'Davido', \
                ['FEM', 'Jowo', 'Something Fishy', 'Holy Ground', 'Heaven', 'Very Special', 'The Best', 'Shopping Spree',\
                 'Sunlight', 'Tanana', 'Mebe', 'La La', 'So Crazy', 'Birthday Cake', 'I Got a Friend', 'Fade', 'On My Way']))
except Exception as error:
    print(error)
                
try:
    cur.execute('INSERT INTO naija_top5 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', \
                 ['Lonely', 'Celebration', 'Focus', 'Count Me Out', 'Oh', 'Oshe', 'Police', \
                  'Door', ' Sugar Mama', 'Consent' ,'Number One ', 'Show Me', 'Runaway' , 'Better Thing']))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (4, 'Back In Office', '2021-10-29', 'Mayorkun', \
                ['Soldier Boy', 'Back In Office',  'Freedom', 'Let Me Know', 'Desire',  'No Strings Attached', \
                 'Holy Father', 'Nakupenda', 'Feel Am', 'Piece Of Mind', 'Jay Jay', 'Oluwa']))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5 (album_id, album_name,  release_date, artist_name, song_name) \
                VALUES (%s, %s, %s, %s, %s)', \
                (5, 'Carpe Diem', '2020-10-8', 'Olamide', \
                ['Another Level', 'GreenLight' 'Infinity', 'Eru', 'Triumphant', 'At Your Service', 'Do Better', \
                'Chimichaga', 'Shilalo', 'Loading', 'Unconditionally', 'Plenty']))
except Exception as error:
    print(error)

try:
    cur.execute('SELECT * FROM naija_top5')
except Exception as error:
    print (error)

row = cur.fetchone()
while row:
    print(row)
    row = cur.fetchone()

(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', ['Reckless', 'Ginger', 'Longtime', 'Mighty Wine', 'Blessed', 'Smile', 'Piece of Me', 'No Stress', 'True Love', 'Sweet One', 'Essence', 'Roma', 'Gyrate', 'Grace'])
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', ['FEM', 'Jowo', 'Something Fishy', 'Holy Ground', 'Heaven', 'Very Special', 'The Best', 'Shopping Spree', 'Sunlight', 'Tanana', 'Mebe', 'La La', 'So Crazy', 'Birthday Cake', 'I Got a Friend', 'Fade', 'On My Way'])
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', ['Lonely', 'Celebration', 'Focus', 'Count Me Out', 'Oh', 'Oshe', 'Police', 'Door', ' Sugar Mama', 'Consent', 'Number One ', 'Show Me', 'Runaway', 'Better Thing'])
(4, 'Back In Office', datetime.date(2021, 10, 29), 'Mayorkun', ['Soldier Boy', 'Back In Office', 'Freedom', 'Let Me Know', 'Desire', 'No Strings Attached', 'Holy Father', 'Nakupenda', 'Feel Am', 'Piece Of Mind', 'Jay Jay', 'Oluwa'])
(5, 'Carpe Diem', datetime.date(2020, 10, 8), 'Olamide', ['Another Level', 'GreenLightInfinity', 'Eru', 'Triumphant', 'At Your Service', 'Do Better', 'Chimichaga', 'Shilalo', 'Loading', 'Unconditionally', 'Plenty'])

**MOVING TO FIRST NORMAL FORM (1NF)**
This data has not been Normalized. To get this data into 1st normal form, we need to remove any collection or list of data. We need to break up the list of songs into individual rows.

- **TABLE NAME** : naija_top5_2
- **column 0**   : album_id
- **column 1**   : album_name
- **column 2**   : release_date
- **column 3**   : artist_name
- **column 4**   : song_name

In [6]:
# Wizkid - Made in Lagos
try:
    cur.execute('CREATE TABLE IF NOT EXISTS naija_top5_2 (album_id int, \
                                                          album_name varchar(200), \
                                                          release_date date, \
                                                          artist_name varchar(200), \
                                                          song_name varchar(200))')
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name, release_date, artist_name, song_name)\
                 VALUES(%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', 'Reckless'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', 'Ginger'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', 'Longtime'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', 'Mighty Wine'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', 'Blessed'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', 'Smile'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', 'Piece of Me'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', 'No Stress'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', 'True Love'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', 'Sweet One'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', 'Essence'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', 'Roma'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', 'Gyrate'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid', 'Grace'))
except Exception as error:
    print(error)

    
# Davido - A Better Time
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'FEM'))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name)\
                 VALUES(%s, %s, %s, %s, %s)',\
                 (2, 'A Better Time', '2020-11-12', 'Davido', 'Jowo'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'Something Fishy'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'Holy Ground'))
except Exception as error:
    print(error)
       
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'Heaven'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'Very Special'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'The Best'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'Shopping Spree'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'Sunlight'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'Tanana'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'Mebe'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'La La'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'So Crazy'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'Birthday Cake'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'I Got a Friend'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'Fade'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (2, 'A Better Time', '2020-11-12', 'Davido', 'On My Way'))
except Exception as error:
    print(error)
    
    
# Joeboy- Somewhere Between Beauty and Magic
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 'Count Me Out'))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 'Focus'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 'Number One'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 'Police'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 'Door'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 'Show me'))
except Exception as error:
    print(error)  
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 'Runaway'))
except Exception as error:
    print(error) 

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 'Lonely'))
except Exception as error:
    print(error) 

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 'Consent'))
except Exception as error:
    print(error) 
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 'Oshe'))
except Exception as error:
    print(error)     
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 'Oh'))
except Exception as error:
    print(error)     
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 'Sugar Mama'))
except Exception as error:
    print(error)  

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 'Better Thing'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 'Celebration'))
except Exception as error:
    print(error)

# Mayorkun - Back In Office
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (4, 'Back In Office', '2021-10-29', 'Mayorkun', 'Soldier Boy'))
except Exception as error:
    print(error)
        
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (4, 'Back In Office', '2021-10-29', 'Mayorkun', 'Back In Office'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (4, 'Back In Office', '2021-10-29', 'Mayorkun', 'Freedom'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (4, 'Back In Office', '2021-10-29', 'Mayorkun', 'Let Me Know'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (4, 'Back In Office', '2021-10-29', 'Mayorkun', 'Desire'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (4, 'Back In Office', '2021-10-29', 'Mayorkun', 'No Strings Attached'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (4, 'Back In Office', '2021-10-29', 'Mayorkun', 'Holy Father'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (4, 'Back In Office', '2021-10-29', 'Mayorkun', 'Nakupenda'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (4, 'Back In Office', '2021-10-29', 'Mayorkun', 'Feel Am'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (4, 'Back In Office', '2021-10-29', 'Mayorkun', 'Piece Of Mind'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (4, 'Back In Office', '2021-10-29', 'Mayorkun', 'Jay Jay'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                 VALUES (%s, %s, %s, %s, %s)',\
                (4, 'Back In Office', '2021-10-29', 'Mayorkun', 'Oluwa'))
except Exception as error:
    print(error)
    
# Olamide - Carpe Diem
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                VALUES (%s, %s, %s, %s, %s)', \
                (5, 'Carpe Diem', '2020-10-08', 'Olamide', 'Another Level'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                VALUES (%s, %s, %s, %s, %s)', \
                (5, 'Carpe Diem', '2020-10-08', 'Olamide', 'Green Light'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                VALUES (%s, %s, %s, %s, %s)', \
                (5, 'Carpe Diem', '2020-10-08', 'Olamide', 'Infinity'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                VALUES (%s, %s, %s, %s, %s)', \
                (5, 'Carpe Diem', '2020-10-08', 'Olamide', 'Eru'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                VALUES (%s, %s, %s, %s, %s)', \
                (5, 'Carpe Diem', '2020-10-08', 'Olamide', 'Triumphant'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                VALUES (%s, %s, %s, %s, %s)', \
                (5, 'Carpe Diem', '2020-10-08', 'Olamide', 'At Your Service'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                VALUES (%s, %s, %s, %s, %s)', \
                (5, 'Carpe Diem', '2020-10-08', 'Olamide', 'Do Better'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                VALUES (%s, %s, %s, %s, %s)', \
                (5, 'Carpe Diem', '2020-10-08', 'Olamide', 'Chimichaga'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                VALUES (%s, %s, %s, %s, %s)', \
                (5, 'Carpe Diem', '2020-10-08', 'Olamide', 'Shilalo'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                VALUES (%s, %s, %s, %s, %s)', \
                (5, 'Carpe Diem', '2020-10-08', 'Olamide', 'Loading'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                VALUES (%s, %s, %s, %s, %s)', \
                (5, 'Carpe Diem', '2020-10-08', 'Olamide', 'Unconditionally'))
except Exception as error:
    print(error)

try: 
    cur.execute('INSERT INTO naija_top5_2 (album_id, album_name,  release_date, artist_name, song_name) \
                VALUES (%s, %s, %s, %s, %s)', \
                (5, 'Carpe Diem', '2020-10-08', 'Olamide', 'Plenty'))
except Exception as error:
    print(error)
    
try: 
    cur.execute('SELECT * FROM naija_top5_2')
except Exception as error:
    print(error)
    
row = cur.fetchone()
while row:
    print(row)
    row = cur.fetchone()

(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', 'Reckless')
(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', 'Ginger')
(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', 'Longtime')
(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', 'Mighty Wine')
(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', 'Blessed')
(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', 'Smile')
(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', 'Piece of Me')
(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', 'No Stress')
(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', 'True Love')
(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', 'Sweet One')
(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', 'Essence')
(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', 'Roma')
(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', 'Gyrate')
(1, 'Made in Lagos', datetime.date(2020, 10, 30), 'Wizkid', 'Grace')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'FEM')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'Jowo')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'Something Fishy')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'Holy Ground')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'Heaven')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'Very Special')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'The Best')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'Shopping Spree')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'Sunlight')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'Tanana')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'Mebe')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'La La')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'So Crazy')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'Birthday Cake')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'I Got a Friend')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'Fade')
(2, 'A Better Time', datetime.date(2020, 11, 12), 'Davido', 'On My Way')
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', 'Count Me Out')
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', 'Focus')
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', 'Number One')
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', 'Police')
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', 'Door')
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', 'Show me')
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', 'Runaway')
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', 'Lonely')
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', 'Consent')
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', 'Oshe')
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', 'Oh')
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', 'Sugar Mama')
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', 'Better Thing')
(3, 'Somewhere Between Beauty and Magic', datetime.date(2021, 2, 4), 'Joeboy', 'Celebration')
(4, 'Back In Office', datetime.date(2021, 10, 29), 'Mayorkun', 'Soldier Boy')
(4, 'Back In Office', datetime.date(2021, 10, 29), 'Mayorkun', 'Back In Office')
(4, 'Back In Office', datetime.date(2021, 10, 29), 'Mayorkun', 'Freedom')
(4, 'Back In Office', datetime.date(2021, 10, 29), 'Mayorkun', 'Let Me Know')
(4, 'Back In Office', datetime.date(2021, 10, 29), 'Mayorkun', 'Desire')
(4, 'Back In Office', datetime.date(2021, 10, 29), 'Mayorkun', 'No Strings Attached')
(4, 'Back In Office', datetime.date(2021, 10, 29), 'Mayorkun', 'Holy Father')
(4, 'Back In Office', datetime.date(2021, 10, 29), 'Mayorkun', 'Nakupenda')
(4, 'Back In Office', datetime.date(2021, 10, 29), 'Mayorkun', 'Feel Am')
(4, 'Back In Office', datetime.date(2021, 10, 29), 'Mayorkun', 'Piece Of Mind')
(4, 'Back In Office', datetime.date(2021, 10, 29), 'Mayorkun', 'Jay Jay')
(4, 'Back In Office', datetime.date(2021, 10, 29), 'Mayorkun', 'Oluwa')
(5, 'Carpe Diem', datetime.date(2020, 10, 8), 'Olamide', 'Another Level')
(5, 'Carpe Diem', datetime.date(2020, 10, 8), 'Olamide', 'Green Light')
(5, 'Carpe Diem', datetime.date(2020, 10, 8), 'Olamide', 'Infinity')
(5, 'Carpe Diem', datetime.date(2020, 10, 8), 'Olamide', 'Eru')
(5, 'Carpe Diem', datetime.date(2020, 10, 8), 'Olamide', 'Triumphant')
(5, 'Carpe Diem', datetime.date(2020, 10, 8), 'Olamide', 'At Your Service')
(5, 'Carpe Diem', datetime.date(2020, 10, 8), 'Olamide', 'Do Better')
(5, 'Carpe Diem', datetime.date(2020, 10, 8), 'Olamide', 'Chimichaga')
(5, 'Carpe Diem', datetime.date(2020, 10, 8), 'Olamide', 'Shilalo')
(5, 'Carpe Diem', datetime.date(2020, 10, 8), 'Olamide', 'Loading')
(5, 'Carpe Diem', datetime.date(2020, 10, 8), 'Olamide', 'Unconditionally')
(5, 'Carpe Diem', datetime.date(2020, 10, 8), 'Olamide', 'Plenty')

**MOVING TO 2ND NORMAL FORM**
- We have moved our data to First Normal Form (1NF) which is the first step of moving to Second Normal Form.
- While our records are Unique, our Primary key (album_id) is not yet unique. This means that our table is not yet in 2NF. 
- We need to break this into 2 tables, album library and song library, The aim is to reduce the number of duplicates we have in album_id.


###### **TABLE NAME** : naija_top5_albums
- **column 0**   : album_id
- **column 1**   : album_name
- **column 2**   : artist_name
- **column 3**   : release_date

In [8]:
try:
    cur.execute('CREATE TABLE IF NOT EXISTS naija_top5_albums (album_id int PRIMARY KEY,\
                                                              album_name varchar(200), \
                                                              release_date varchar(200), \
                                                              artist_name varchar(200))')
except Exception as error:
    print(error)

# Wizkid - Ma de in Lagos
try:
    cur.execute('INSERT INTO naija_top5_albums (album_id, album_name, release_date, artist_name)\
                 VALUES(%s, %s, %s, %s)', \
                (1, 'Made in Lagos', '2020-10-30', 'Wizkid'))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_albums (album_id, album_name, release_date, artist_name)\
                 VALUES(%s, %s, %s, %s)', \
                (2, 'A Better Time', '2020-11-12', 'Davido'))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_albums (album_id, album_name, release_date, artist_name)\
                 VALUES(%s, %s, %s, %s)', \
                (3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy'))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_albums (album_id, album_name, release_date, artist_name)\
                 VALUES(%s, %s, %s, %s)', \
                (4, 'Back In Office', '2021-10-29', 'Mayorkun'))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_albums (album_id, album_name, release_date, artist_name)\
                 VALUES(%s, %s, %s, %s)', \
                (5, 'Carpe Diem', '2020-10-08', 'Olamide'))
except Exception as error:
    print(error)

try:
    cur.execute('SELECT * FROM naija_top5_albums')
except Exception as error:
    print(error)

row = cur.fetchone()
while row:
    print(row)
    row = cur.fetchone()

(1, 'Made in Lagos', '2020-10-30', 'Wizkid')
(2, 'A Better Time', '2020-11-12', 'Davido')
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy')
(4, 'Back In Office', '2021-10-29', 'Mayorkun')
(5, 'Carpe Diem', '2020-10-08', 'Olamide')

**TABLE NAME** : naija_top5_album_songs
- column 0 : song_id
- column 1 : song_name
- column 2 : artist_name
- column 3 : album_id

In [9]:
try:
    cur.execute('CREATE TABLE IF NOT EXISTS naija_top5_album_songs (song_id int PRIMARY KEY, \
                                                              song_name varchar(200), \
                                                              artist_name varchar(200), \
                                                              album_id int, \
                                                              FOREIGN KEY(album_id) REFERENCES naija_top5_albums(album_id))')
except Exception as error:
    print(error)

# Wizkid - Made in Lagos
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (1, 'Reckless','Wizkid', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (2, 'Ginger','Wizkid', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (3, 'Longtime','Wizkid', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (4, 'Mighty Wine','Wizkid', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (5, 'Blessed','Wizkid', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (6, 'Smile','Wizkid', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (7, 'Piece of Me','Wizkid', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (8, 'No Stress','Wizkid', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (9, 'True Love','Wizkid', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (10, 'Sweet One','Wizkid', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (11, 'Essence','Wizkid', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (12, 'Roma','Wizkid', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (13, 'Gyrate','Wizkid', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (14, 'Grace','Wizkid', 1))
except Exception as error:
    print(error)
    
# Davido - A Better Time
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (15, 'FEM', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (16, 'Jowo', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (17, 'Something Fishy', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (18, 'Holy Ground', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (19, 'Heaven', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (20, 'Very Special', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (21, 'The Best', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (22, 'Shopping Spree', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (23, 'Sunlight', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (24, 'Tanana', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (25, 'Mebe', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (26, 'La La', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (27, 'So Crazy', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (28, 'Birthday Cake', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (29, 'I Got a Friend', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (30, 'Fade', 'Davido', 2))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (31, 'On My Way', 'Davido', 2))
except Exception as error:
    print(error)

# Joeboy- Somewhere Between Beauty and Magic
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (32, 'Count Me Out', 'Joeboy', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (33, 'Focus', 'Joeboy', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (34, 'Number One', 'Joeboy', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (35, 'Police', 'Joeboy', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (36, 'Door', 'Joeboy', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (37, 'Show me', 'Joeboy', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (38, 'Runaway', 'Joeboy', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (39, 'Lonely', 'Joeboy', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (40, 'Consent', 'Joeboy', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (41, 'Oshe', 'Joeboy', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (42, 'Oh', 'Joeboy', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (43, 'Sugar Mama', 'Joeboy', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (44, 'Better Thing', 'Joeboy', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (45, 'Celebration', 'Joeboy', 3))
except Exception as error:
    print(error)
    
# Mayorkun - Back In Office
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (46, 'Soldier Boy', 'Mayorkun', 4))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (47, 'Back In Office', 'Mayorkun', 4))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (48, 'Freedom', 'Mayorkun', 4))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (49, 'Let Me Know', 'Mayorkun', 4))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (50, 'Desire', 'Mayorkun', 4))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (51, 'No Strings Attached', 'Mayorkun', 4))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (52, 'Holy Father', 'Mayorkun', 4))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (53, 'Nakupenda', 'Mayorkun', 4))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (54, 'Feel Am', 'Mayorkun', 4))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (55, 'Piece Of Mind', 'Mayorkun', 4))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (56, 'Jay Jay', 'Mayorkun', 4))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (57, 'Oluwa', 'Mayorkun', 4))
except Exception as error:
    print(error)
    
# Olamide - Carpe Diem
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (58, 'Another Level', 'Olamide', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (59, 'Green Light', 'Olamide', 5))
except Exception as error:
    print(error)


try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (60, 'Infinity', 'Olamide', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (61, 'Eru', 'Olamide', 5))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (62, 'Triumphant', 'Olamide', 5))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (63, 'At Your Service', 'Olamide', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (64, 'Do Better', 'Olamide', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (65, 'Chimichaga', 'Olamide', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (66, 'Shilalo', 'Olamide', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (67, 'Loading', 'Olamide', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (68, 'Unconditionally', 'Olamide', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_songs(song_id, song_name, artist_name, album_id) \
                 VALUES(%s, %s, %s, %s)', \
                 (69, 'Plenty', 'Olamide', 5))
except Exception as error:
    print(error)

try: 
    cur.execute('SELECT * FROM naija_top5_album_songs')
except Exception as error:
    print(error)
    
row = cur.fetchone()
while row:
    print(row)
    row = cur.fetchone()

(1, 'Reckless', 'Wizkid', 1)
(2, 'Ginger', 'Wizkid', 1)
(3, 'Longtime', 'Wizkid', 1)
(4, 'Mighty Wine', 'Wizkid', 1)
(5, 'Blessed', 'Wizkid', 1)
(6, 'Smile', 'Wizkid', 1)
(7, 'Piece of Me', 'Wizkid', 1)
(8, 'No Stress', 'Wizkid', 1)
(9, 'True Love', 'Wizkid', 1)
(10, 'Sweet One', 'Wizkid', 1)
(11, 'Essence', 'Wizkid', 1)
(12, 'Roma', 'Wizkid', 1)
(13, 'Gyrate', 'Wizkid', 1)
(14, 'Grace', 'Wizkid', 1)
(15, 'FEM', 'Davido', 2)
(16, 'Jowo', 'Davido', 2)
(17, 'Something Fishy', 'Davido', 2)
(18, 'Holy Ground', 'Davido', 2)
(19, 'Heaven', 'Davido', 2)
(20, 'Very Special', 'Davido', 2)
(21, 'The Best', 'Davido', 2)
(22, 'Shopping Spree', 'Davido', 2)
(23, 'Sunlight', 'Davido', 2)
(24, 'Tanana', 'Davido', 2)
(25, 'Mebe', 'Davido', 2)
(26, 'La La', 'Davido', 2)
(27, 'So Crazy', 'Davido', 2)
(28, 'Birthday Cake', 'Davido', 2)
(29, 'I Got a Friend', 'Davido', 2)
(30, 'Fade', 'Davido', 2)
(31, 'On My Way', 'Davido', 2)
(32, 'Count Me Out', 'Joeboy', 3)
(33, 'Focus', 'Joeboy', 3)
(34, 'Number One', 'Joeboy', 3)
(35, 'Police', 'Joeboy', 3)
(36, 'Door', 'Joeboy', 3)
(37, 'Show me', 'Joeboy', 3)
(38, 'Runaway', 'Joeboy', 3)
(39, 'Lonely', 'Joeboy', 3)
(40, 'Consent', 'Joeboy', 3)
(41, 'Oshe', 'Joeboy', 3)
(42, 'Oh', 'Joeboy', 3)
(43, 'Sugar Mama', 'Joeboy', 3)
(44, 'Better Thing', 'Joeboy', 3)
(45, 'Celebration', 'Joeboy', 3)
(46, 'Soldier Boy', 'Mayorkun', 4)
(47, 'Back In Office', 'Mayorkun', 4)
(48, 'Freedom', 'Mayorkun', 4)
(49, 'Let Me Know', 'Mayorkun', 4)
(50, 'Desire', 'Mayorkun', 4)
(51, 'No Strings Attached', 'Mayorkun', 4)
(52, 'Holy Father', 'Mayorkun', 4)
(53, 'Nakupenda', 'Mayorkun', 4)
(54, 'Feel Am', 'Mayorkun', 4)
(55, 'Piece Of Mind', 'Mayorkun', 4)
(56, 'Jay Jay', 'Mayorkun', 4)
(57, 'Oluwa', 'Mayorkun', 4)
(58, 'Another Level', 'Olamide', 5)
(59, 'Green Light', 'Olamide', 5)
(60, 'Infinity', 'Olamide', 5)
(61, 'Eru', 'Olamide', 5)
(62, 'Triumphant', 'Olamide', 5)
(63, 'At Your Service', 'Olamide', 5)
(64, 'Do Better', 'Olamide', 5)
(65, 'Chimichaga', 'Olamide', 5)
(66, 'Shilalo', 'Olamide', 5)
(67, 'Loading', 'Olamide', 5)
(68, 'Unconditionally', 'Olamide', 5)
(69, 'Plenty', 'Olamide', 5)

**Let's do a join so we can get all the information we had in our first table.**

In [10]:
try:
    cur.execute('Select * from naija_top5_albums join \
                 naija_top5_album_songs on naija_top5_albums.album_id = naija_top5_album_songs.album_id')
except Exceptions as error:
    print(error)

row = cur.fetchone()
while row:
    print(row)
    row = cur.fetchone()

(1, 'Made in Lagos', '2020-10-30', 'Wizkid', 1, 'Reckless', 'Wizkid', 1)
(1, 'Made in Lagos', '2020-10-30', 'Wizkid', 2, 'Ginger', 'Wizkid', 1)
(1, 'Made in Lagos', '2020-10-30', 'Wizkid', 3, 'Longtime', 'Wizkid', 1)
(1, 'Made in Lagos', '2020-10-30', 'Wizkid', 4, 'Mighty Wine', 'Wizkid', 1)
(1, 'Made in Lagos', '2020-10-30', 'Wizkid', 5, 'Blessed', 'Wizkid', 1)
(1, 'Made in Lagos', '2020-10-30', 'Wizkid', 6, 'Smile', 'Wizkid', 1)
(1, 'Made in Lagos', '2020-10-30', 'Wizkid', 7, 'Piece of Me', 'Wizkid', 1)
(1, 'Made in Lagos', '2020-10-30', 'Wizkid', 8, 'No Stress', 'Wizkid', 1)
(1, 'Made in Lagos', '2020-10-30', 'Wizkid', 9, 'True Love', 'Wizkid', 1)
(1, 'Made in Lagos', '2020-10-30', 'Wizkid', 10, 'Sweet One', 'Wizkid', 1)
(1, 'Made in Lagos', '2020-10-30', 'Wizkid', 11, 'Essence', 'Wizkid', 1)
(1, 'Made in Lagos', '2020-10-30', 'Wizkid', 12, 'Roma', 'Wizkid', 1)
(1, 'Made in Lagos', '2020-10-30', 'Wizkid', 13, 'Gyrate', 'Wizkid', 1)
(1, 'Made in Lagos', '2020-10-30', 'Wizkid', 14, 'Grace', 'Wizkid', 1)
(2, 'A Better Time', '2020-11-12', 'Davido', 15, 'FEM', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 16, 'Jowo', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 17, 'Something Fishy', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 18, 'Holy Ground', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 19, 'Heaven', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 20, 'Very Special', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 21, 'The Best', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 22, 'Shopping Spree', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 23, 'Sunlight', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 24, 'Tanana', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 25, 'Mebe', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 26, 'La La', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 27, 'So Crazy', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 28, 'Birthday Cake', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 29, 'I Got a Friend', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 30, 'Fade', 'Davido', 2)
(2, 'A Better Time', '2020-11-12', 'Davido', 31, 'On My Way', 'Davido', 2)
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 32, 'Count Me Out', 'Joeboy', 3)
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 33, 'Focus', 'Joeboy', 3)
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 34, 'Number One', 'Joeboy', 3)
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 35, 'Police', 'Joeboy', 3)
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 36, 'Door', 'Joeboy', 3)
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 37, 'Show me', 'Joeboy', 3)
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 38, 'Runaway', 'Joeboy', 3)
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 39, 'Lonely', 'Joeboy', 3)
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 40, 'Consent', 'Joeboy', 3)
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 41, 'Oshe', 'Joeboy', 3)
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 42, 'Oh', 'Joeboy', 3)
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 43, 'Sugar Mama', 'Joeboy', 3)
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 44, 'Better Thing', 'Joeboy', 3)
(3, 'Somewhere Between Beauty and Magic', '2021-02-04', 'Joeboy', 45, 'Celebration', 'Joeboy', 3)
(4, 'Back In Office', '2021-10-29', 'Mayorkun', 46, 'Soldier Boy', 'Mayorkun', 4)
(4, 'Back In Office', '2021-10-29', 'Mayorkun', 47, 'Back In Office', 'Mayorkun', 4)
(4, 'Back In Office', '2021-10-29', 'Mayorkun', 48, 'Freedom', 'Mayorkun', 4)
(4, 'Back In Office', '2021-10-29', 'Mayorkun', 49, 'Let Me Know', 'Mayorkun', 4)
(4, 'Back In Office', '2021-10-29', 'Mayorkun', 50, 'Desire', 'Mayorkun', 4)
(4, 'Back In Office', '2021-10-29', 'Mayorkun', 51, 'No Strings Attached', 'Mayorkun', 4)
(4, 'Back In Office', '2021-10-29', 'Mayorkun', 52, 'Holy Father', 'Mayorkun', 4)
(4, 'Back In Office', '2021-10-29', 'Mayorkun', 53, 'Nakupenda', 'Mayorkun', 4)
(4, 'Back In Office', '2021-10-29', 'Mayorkun', 54, 'Feel Am', 'Mayorkun', 4)
(4, 'Back In Office', '2021-10-29', 'Mayorkun', 55, 'Piece Of Mind', 'Mayorkun', 4)
(4, 'Back In Office', '2021-10-29', 'Mayorkun', 56, 'Jay Jay', 'Mayorkun', 4)
(4, 'Back In Office', '2021-10-29', 'Mayorkun', 57, 'Oluwa', 'Mayorkun', 4)
(5, 'Carpe Diem', '2020-10-08', 'Olamide', 58, 'Another Level', 'Olamide', 5)
(5, 'Carpe Diem', '2020-10-08', 'Olamide', 59, 'Green Light', 'Olamide', 5)
(5, 'Carpe Diem', '2020-10-08', 'Olamide', 60, 'Infinity', 'Olamide', 5)
(5, 'Carpe Diem', '2020-10-08', 'Olamide', 61, 'Eru', 'Olamide', 5)
(5, 'Carpe Diem', '2020-10-08', 'Olamide', 62, 'Triumphant', 'Olamide', 5)
(5, 'Carpe Diem', '2020-10-08', 'Olamide', 63, 'At Your Service', 'Olamide', 5)
(5, 'Carpe Diem', '2020-10-08', 'Olamide', 64, 'Do Better', 'Olamide', 5)
(5, 'Carpe Diem', '2020-10-08', 'Olamide', 65, 'Chimichaga', 'Olamide', 5)
(5, 'Carpe Diem', '2020-10-08', 'Olamide', 66, 'Shilalo', 'Olamide', 5)
(5, 'Carpe Diem', '2020-10-08', 'Olamide', 67, 'Loading', 'Olamide', 5)
(5, 'Carpe Diem', '2020-10-08', 'Olamide', 68, 'Unconditionally', 'Olamide', 5)
(5, 'Carpe Diem', '2020-10-08', 'Olamide', 69, 'Plenty', 'Olamide', 5)

**MOVING TO 3RD NORMAL FORM**
###### Our tables still have transitive functional dependency, They are not in 3NF
###### naija_top5_albums can now move artist_name to its own table called Artists, which will leave us with 3 tables.
###### CREATE THE 3 TABLES

- **TABLE NAME** : naija_top5_album_library
- **column 0**   : album_id
- **column 1**   : album_name
- **column 2**   : artist_id
- **column 3**   : release_date






- **TABLE NAME** : naija_top5_song_library
- **column 0**   : song_id
- **column 1**   : song_name
- **column 2**   : album_id






- **TABLE NAME** : naija_top5_artist_library
- **column 0**   : artist_id
- **column 1**   : artist_name

In [11]:
try:
    cur.execute('CREATE TABLE IF NOT EXISTS naija_top5_artist_library(artist_id int PRIMARY KEY, \
                                                                      artist_name varchar(200))')
except Exception as error:
    print(error)

try:
    cur.execute('CREATE TABLE IF NOT EXISTS naija_top5_album_library(album_id int PRIMARY KEY, \
                                                                      album_name varchar(200), \
                                                                      artist_id int, \
                                                                      release_date date, \
                                                                      FOREIGN KEY(artist_id) \
                                                                      REFERENCES naija_top5_artist_library(artist_id))')
except Exception as error:
    print(error)

try:
    cur.execute('CREATE TABLE IF NOT EXISTS naija_top5_song_library(song_id int PRIMARY KEY, \
                                                                    song_name varchar(200), \
                                                                    album_id int, \
                                                                    FOREIGN KEY(album_id) \
                                                                    REFERENCES naija_top5_album_library(album_id))')
except Exception as error:
    print(error)

###### INSERT YOUR RECORDS

In [12]:
# naija_top5_artist_library
try:
    cur.execute('INSERT INTO naija_top5_artist_library(artist_id, artist_name) \
                 VALUES(%s, %s)', \
                 (1, 'Wizkid'))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_artist_library(artist_id, artist_name) \
                 VALUES(%s, %s)', \
                 (2, 'Davido'))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_artist_library(artist_id, artist_name) \
                 VALUES(%s, %s)', \
                 (3, 'Joeboy'))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_artist_library(artist_id, artist_name) \
                 VALUES(%s, %s)', \
                 (4, 'Mayorkun'))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_artist_library(artist_id, artist_name) \
                 VALUES(%s, %s)', \
                 (5, 'Olamide'))
except Exception as error:
    print(error)
    
    
# naija_top5_album_library
try:
    cur.execute('INSERT INTO naija_top5_album_library(album_id, album_name, artist_id, release_date) \
                 VALUES(%s, %s, %s, %s)', \
                 (1, 'Made in Lagos', 1, '2020-10-30'))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_library(album_id, album_name, artist_id, release_date) \
                 VALUES(%s, %s, %s, %s)', \
                 (2, 'A Better Time', 2, '2020-11-12'))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_library(album_id, album_name, artist_id, release_date) \
                 VALUES(%s, %s, %s, %s)', \
                 (3, 'Somewhere Between Beauty and Magic', 3, '2021-02-04'))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_album_library(album_id, album_name, artist_id, release_date) \
                 VALUES(%s, %s, %s, %s)', \
                 (4, 'Back In Office', 4, '2021-10-29'))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_album_library(album_id, album_name, artist_id, release_date) \
                 VALUES(%s, %s, %s, %s)', \
                 (5, 'Carpe Diem', 5, '2020-10-08'))
except Exception as error:
    print(error)
    
    
# naija_top5_song_library
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (1, 'Reckless', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (2, 'Ginger', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (3, 'Longtime', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (4, 'Mighty Wine', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (5, 'Blessed', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (6, 'Smile', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (7, 'Piece of Me', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (8, 'No Stress', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (9, 'True Love', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (10, 'Sweet One', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (11, 'Essence', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (12, 'Roma', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (13, 'Gyrate', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (14, 'Grace', 1))
except Exception as error:
    print(error)
    
try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (15, 'FEM', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (16, 'Jowo', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (17, 'Something Fishy', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (18, 'Holy Ground', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (19, 'Heaven', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (20, 'Very Special', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (21, 'The Best', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (22, 'Shopping Spree', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (23, 'Sunlight', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (24, 'Tanana', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (25, 'Mebe', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (26, 'La La', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (27, 'So Crazy', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (28, 'Birthday Cake', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (29, 'I Got a Friend', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (30, 'Fade', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (31, 'On My Way', 2))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (32, 'Count Me Out', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (33, 'Focus', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (34, 'Number One', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (35, 'Police', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (36, 'Door', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (37, 'Show me', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (38, 'Runaway', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (39, 'Lonely', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (40, 'Consent', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (41, 'Oshe', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (42, 'Oh', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (43, 'Sugar Mama', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (44, 'Better Thing', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (45, 'Celebration', 3))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (46, 'Soldier Boy', 4))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (47, 'Back In Office', 4))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (48, 'Freedom', 4))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (49, 'Let Me Know', 4))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (50, 'Desire', 4))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (51, 'No Strings Attached', 4))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (52, 'Holy Father', 4))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (53, 'Nakupenda', 4))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (54, 'Feel Am', 4))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (55, 'Piece Of Mind', 4))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (56, 'Jay Jay', 4))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (57, 'Oluwa', 4))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (58, 'Another Level', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (59, 'Green Light', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (60, 'Infinity', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (61, 'Eru', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (62, 'Triumphant', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (63, 'At Your Service', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (64, 'Do Better', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (65, 'Chimichaga', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (66, 'Shilalo', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (67, 'Loading', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (68, 'Unconditionally', 5))
except Exception as error:
    print(error)

try:
    cur.execute('INSERT INTO naija_top5_song_library(song_id, song_name, album_id) \
                 VALUES(%s, %s, %s)', \
                 (69, 'Plenty', 5))
except Exception as error:
    print(error)

try: 
    cur.execute('SELECT * FROM naija_top5_album_songs')
except Exception as error:
    print(error)
    
row = cur.fetchone()
while row:
    print(row)
    row = cur.fetchone()

(1, 'Reckless', 'Wizkid', 1)
(2, 'Ginger', 'Wizkid', 1)
(3, 'Longtime', 'Wizkid', 1)
(4, 'Mighty Wine', 'Wizkid', 1)
(5, 'Blessed', 'Wizkid', 1)
(6, 'Smile', 'Wizkid', 1)
(7, 'Piece of Me', 'Wizkid', 1)
(8, 'No Stress', 'Wizkid', 1)
(9, 'True Love', 'Wizkid', 1)
(10, 'Sweet One', 'Wizkid', 1)
(11, 'Essence', 'Wizkid', 1)
(12, 'Roma', 'Wizkid', 1)
(13, 'Gyrate', 'Wizkid', 1)
(14, 'Grace', 'Wizkid', 1)
(15, 'FEM', 'Davido', 2)
(16, 'Jowo', 'Davido', 2)
(17, 'Something Fishy', 'Davido', 2)
(18, 'Holy Ground', 'Davido', 2)
(19, 'Heaven', 'Davido', 2)
(20, 'Very Special', 'Davido', 2)
(21, 'The Best', 'Davido', 2)
(22, 'Shopping Spree', 'Davido', 2)
(23, 'Sunlight', 'Davido', 2)
(24, 'Tanana', 'Davido', 2)
(25, 'Mebe', 'Davido', 2)
(26, 'La La', 'Davido', 2)
(27, 'So Crazy', 'Davido', 2)
(28, 'Birthday Cake', 'Davido', 2)
(29, 'I Got a Friend', 'Davido', 2)
(30, 'Fade', 'Davido', 2)
(31, 'On My Way', 'Davido', 2)
(32, 'Count Me Out', 'Joeboy', 3)
(33, 'Focus', 'Joeboy', 3)
(34, 'Number One', 'Joeboy', 3)
(35, 'Police', 'Joeboy', 3)
(36, 'Door', 'Joeboy', 3)
(37, 'Show me', 'Joeboy', 3)
(38, 'Runaway', 'Joeboy', 3)
(39, 'Lonely', 'Joeboy', 3)
(40, 'Consent', 'Joeboy', 3)
(41, 'Oshe', 'Joeboy', 3)
(42, 'Oh', 'Joeboy', 3)
(43, 'Sugar Mama', 'Joeboy', 3)
(44, 'Better Thing', 'Joeboy', 3)
(45, 'Celebration', 'Joeboy', 3)
(46, 'Soldier Boy', 'Mayorkun', 4)
(47, 'Back In Office', 'Mayorkun', 4)
(48, 'Freedom', 'Mayorkun', 4)
(49, 'Let Me Know', 'Mayorkun', 4)
(50, 'Desire', 'Mayorkun', 4)
(51, 'No Strings Attached', 'Mayorkun', 4)
(52, 'Holy Father', 'Mayorkun', 4)
(53, 'Nakupenda', 'Mayorkun', 4)
(54, 'Feel Am', 'Mayorkun', 4)
(55, 'Piece Of Mind', 'Mayorkun', 4)
(56, 'Jay Jay', 'Mayorkun', 4)
(57, 'Oluwa', 'Mayorkun', 4)
(58, 'Another Level', 'Olamide', 5)
(59, 'Green Light', 'Olamide', 5)
(60, 'Infinity', 'Olamide', 5)
(61, 'Eru', 'Olamide', 5)
(62, 'Triumphant', 'Olamide', 5)
(63, 'At Your Service', 'Olamide', 5)
(64, 'Do Better', 'Olamide', 5)
(65, 'Chimichaga', 'Olamide', 5)
(66, 'Shilalo', 'Olamide', 5)
(67, 'Loading', 'Olamide', 5)
(68, 'Unconditionally', 'Olamide', 5)
(69, 'Plenty', 'Olamide', 5)

In [14]:
conn.close()
cur.close()